version: "3.3"

services:
  server:
    image: golang:1.14.4
    working_dir: /go/src/go-backend
    command: make server-up
    tty: true
    volumes:
    - ../:/go/src/
    env_file:
      - config/config.env
    ports:
    - "3333:3333"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    env_file:
      - config/database.env
    ports:
    - "8601:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"

  proxy:
    image: nginx:1.13-alpine
    restart: unless-stopped
    volumes:
    - ./config/proxy_conf.nginx:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres

volumes:
  database-data:
